#!/usr/bin/sh
git config --global user.email "a05558@126.com"
git config --global user.name "a05558"
echo "Input File: "
read st
git add $st
echo "Input Update: "
read str
git commit -m $str
git push origin master
